name: Plagiarism Checker

on:
  pull_request:
    paths:
      - "games/**/*.js"

jobs:
  plagiarism-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'

      - name: Delete existing package.json
        run: |
          if [ -f "package.json" ]; then
            rm package.json
          fi

      - name: Create new package.json for plagiarism checker
        run: |
          cat > package.json <<EOL
          {
            "name": "plagiarism-checker",
            "version": "1.0.0",
            "description": "A script to check for plagiarism using MOSS.",
            "main": ".github/scripts/plagiarism_check.cjs",
            "dependencies": {
              "axios": "^1.0.0",
              "cheerio": "^1.0.0"
            },
            "scripts": {
              "start": "node .github/scripts/plagiarism_check.cjs"
            }
          }
          EOL

      - name: Install Dependencies for Plagiarism Checker
        run: npm install

      - name: Print Base and Head SHA
        run: |
          echo "Pull Request Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Pull Request Head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Get list of changed files
        id: changed-files
        run: |
          js_files=$(git diff --name-only --diff-filter=AM --find-renames --find-copies ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^games/.*\.js$' | xargs)
          echo "FILES=$js_files" >> $GITHUB_ENV

      - name: Inject MOSS User ID into moss.pl
        run: |
          sed -i "s/\$userid=;/\$userid=${{ secrets.MOSS_USERID }};/" .github/scripts/moss.pl

      - name: Run Plagiarism Detection Script
        id: plagiarism-check
        if: ${{ env.FILES != '' }}
        run: npm start "${{ env.FILES }}"

      - name: Upload MOSS Results as Artifacts
        if: success() && ${{ env.FILES != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: moss-results
          path: .github/moss_results/

      - name: Upload Plagiarism Report as Artifact
        if: success() && ${{ env.FILES != '' }} && steps.plagiarism-check.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: plagiarism-report
          path: .github/moss_results/plagiarism-report.md