name: Plagiarism Checker

on:
  pull_request:
    paths:
      - "games/**/*.js"

jobs:
  plagiarism-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'

      - name: Rebuild package.json for Plagiarism Checker
        run: |
          if [ -f "package.json" ]; then
            rm package.json
          fi
          cat > package.json <<EOL
          {
            "name": "plagiarism-checker",
            "version": "1.0.0",
            "description": "A script to check for plagiarism using MOSS.",
            "main": ".github/scripts/plagiarism_check.cjs",
            "dependencies": {
              "axios": "^1.0.0",
              "cheerio": "^1.0.0"
            },
            "scripts": {
              "start": "node .github/scripts/plagiarism_check.cjs"
            }
          }
          EOL

      - name: Install NPM Dependencies
        run: npm install

      - name: Identify Changed JavaScript Files
        id: changed-files
        run: |
          js_files=$(git diff --name-only --diff-filter=AM --find-renames --find-copies ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^games/.*\.js$' | xargs)
          echo "FILES=$js_files" >> $GITHUB_ENV
        shell: bash

      - name: Show Git Base and Head SHAs
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Set Up MOSS Script
        run: sed -i "s/\$userid=;/\$userid=547529030;/" .github/scripts/moss.pl

      - name: Run Plagiarism Detection
        id: plagiarism-check
        if: ${{ env.FILES != '' }}
        run: npm start "${{ env.FILES }}"

      - name: Upload MOSS Results
        if: success() && ${{ env.FILES != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: moss-results
          path: .github/moss_results/

      - name: Upload Detailed Plagiarism Report
        if: success() && ${{ env.FILES != '' }} && steps.plagiarism-check.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: plagiarism-report
          path: .github/moss_results/plagiarism-report.md

      - name: Save Pull Request Number
        if: always()
        run: echo ${{ github.event.pull_request.number }} > pr_number.txt

      - name: Upload PR Number Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr_number.txt